language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy3.6-7.3.1"

install:
  - pip install --upgrade pip
  - pip --version
  - travis_retry pip install pytest-flake8
  - python setup.py install

script:
  - py.test -v --flake8 extenum tests
