language: python
sudo: false

env:
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy3

install:
  - pip install --upgrade pip
  - travis_retry pip install --use-mirrors tox

script:
  - travis_retry tox
