language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3.5"

install:
  - pip install --upgrade pip
  - pip --version
  - travis_retry pip install pytest-pep8 pytest-flakes

script:
  - py.test -v --pep8 --flakes extenum tests
