language: python
sudo: false
python: 3.6

env:
  matrix:
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=pypy3.5

install:
  - pip install --upgrade pip
  - pip --version
  - travis_retry pip install tox

script:
  - travis_retry tox
